/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const students_subjects = sqliteTable(
  "students_subjects",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    subject: text("subject").notNull(),
  },
  (columns) => [
    index("students_subjects_order_idx").on(columns._order),
    index("students_subjects_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [students.id],
      name: "students_subjects_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const students = sqliteTable(
  "students",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    class: text("class"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    email: text("email"),
    phone: text("phone"),
    attendance: numeric("attendance", { mode: "number" }).default(100),
    avgTestScore: numeric("avg_test_score", { mode: "number" }),
    courseProgress: numeric("course_progress", { mode: "number" }).default(0),
    notes: text("notes"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("students_avatar_idx").on(columns.avatar),
    index("students_updated_at_idx").on(columns.updatedAt),
    index("students_created_at_idx").on(columns.createdAt),
  ],
);

export const materials_tags = sqliteTable(
  "materials_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    tag: text("tag", {
      enum: ["homework", "test", "summary", "video", "formulas", "oge", "ege"],
    }),
  },
  (columns) => [
    index("materials_tags_order_idx").on(columns._order),
    index("materials_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [materials.id],
      name: "materials_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const materials = sqliteTable(
  "materials",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    type: text("type", {
      enum: ["pdf", "doc", "image", "video", "link", "note"],
    }).notNull(),
    category: text("category", { enum: ["5", "6", "7", "8", "9", "10", "11"] }),
    subject: text("subject", { enum: ["algebra", "geometry", "math"] }),
    topic: text("topic"),
    file: integer("file_id").references(() => media.id, {
      onDelete: "set null",
    }),
    fileUrl: text("file_url"),
    content: text("content"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("materials_file_idx").on(columns.file),
    index("materials_updated_at_idx").on(columns.updatedAt),
    index("materials_created_at_idx").on(columns.createdAt),
  ],
);

export const homework = sqliteTable(
  "homework",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    student: integer("student_id")
      .notNull()
      .references(() => students.id, {
        onDelete: "set null",
      }),
    material: integer("material_id").references(() => materials.id, {
      onDelete: "set null",
    }),
    status: text("status", { enum: ["active", "review", "checked", "overdue"] })
      .notNull()
      .default("active"),
    dueDate: text("due_date")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    instructions: text("instructions"),
    submittedDate: text("submitted_date").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    submissionType: text("submission_type", {
      enum: ["text", "image", "file"],
    }),
    submissionContent: text("submission_content"),
    submissionFile: integer("submission_file_id").references(() => media.id, {
      onDelete: "set null",
    }),
    grade: numeric("grade", { mode: "number" }),
    teacherComment: text("teacher_comment"),
    studentComment: text("student_comment"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("homework_student_idx").on(columns.student),
    index("homework_material_idx").on(columns.material),
    index("homework_submission_file_idx").on(columns.submissionFile),
    index("homework_updated_at_idx").on(columns.updatedAt),
    index("homework_created_at_idx").on(columns.createdAt),
  ],
);

export const tests_questions_options = sqliteTable(
  "tests_questions_options",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    option: text("option"),
  },
  (columns) => [
    index("tests_questions_options_order_idx").on(columns._order),
    index("tests_questions_options_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tests_questions.id],
      name: "tests_questions_options_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tests_questions_correct_answers = sqliteTable(
  "tests_questions_correct_answers",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    answer: text("answer").notNull(),
  },
  (columns) => [
    index("tests_questions_correct_answers_order_idx").on(columns._order),
    index("tests_questions_correct_answers_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tests_questions.id],
      name: "tests_questions_correct_answers_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tests_questions = sqliteTable(
  "tests_questions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    text: text("text").notNull(),
    type: text("type", {
      enum: ["single-choice", "multiple-choice", "text-input"],
    }).notNull(),
  },
  (columns) => [
    index("tests_questions_order_idx").on(columns._order),
    index("tests_questions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tests.id],
      name: "tests_questions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tests = sqliteTable(
  "tests",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    description: text("description"),
    subject: text("subject", {
      enum: ["algebra", "geometry", "math"],
    }).notNull(),
    topic: text("topic"),
    timeLimitMinutes: numeric("time_limit_minutes", { mode: "number" }).default(
      0,
    ),
    passThreshold: numeric("pass_threshold", { mode: "number" }).default(75),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("tests_updated_at_idx").on(columns.updatedAt),
    index("tests_created_at_idx").on(columns.createdAt),
  ],
);

export const payments = sqliteTable(
  "payments",
  {
    id: integer("id").primaryKey(),
    student: integer("student_id")
      .notNull()
      .references(() => students.id, {
        onDelete: "set null",
      }),
    tariff: text("tariff").notNull(),
    amount: numeric("amount", { mode: "number" }).notNull(),
    status: text("status", { enum: ["pending", "paid", "overdue"] })
      .notNull()
      .default("pending"),
    dueDate: text("due_date").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    paidDate: text("paid_date").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    notes: text("notes"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payments_student_idx").on(columns.student),
    index("payments_updated_at_idx").on(columns.updatedAt),
    index("payments_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    studentsID: integer("students_id"),
    materialsID: integer("materials_id"),
    homeworkID: integer("homework_id"),
    testsID: integer("tests_id"),
    paymentsID: integer("payments_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_students_id_idx").on(
      columns.studentsID,
    ),
    index("payload_locked_documents_rels_materials_id_idx").on(
      columns.materialsID,
    ),
    index("payload_locked_documents_rels_homework_id_idx").on(
      columns.homeworkID,
    ),
    index("payload_locked_documents_rels_tests_id_idx").on(columns.testsID),
    index("payload_locked_documents_rels_payments_id_idx").on(
      columns.paymentsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["studentsID"]],
      foreignColumns: [students.id],
      name: "payload_locked_documents_rels_students_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["materialsID"]],
      foreignColumns: [materials.id],
      name: "payload_locked_documents_rels_materials_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["homeworkID"]],
      foreignColumns: [homework.id],
      name: "payload_locked_documents_rels_homework_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["testsID"]],
      foreignColumns: [tests.id],
      name: "payload_locked_documents_rels_tests_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["paymentsID"]],
      foreignColumns: [payments.id],
      name: "payload_locked_documents_rels_payments_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_students_subjects = relations(
  students_subjects,
  ({ one }) => ({
    _parentID: one(students, {
      fields: [students_subjects._parentID],
      references: [students.id],
      relationName: "subjects",
    }),
  }),
);
export const relations_students = relations(students, ({ one, many }) => ({
  avatar: one(media, {
    fields: [students.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  subjects: many(students_subjects, {
    relationName: "subjects",
  }),
}));
export const relations_materials_tags = relations(
  materials_tags,
  ({ one }) => ({
    _parentID: one(materials, {
      fields: [materials_tags._parentID],
      references: [materials.id],
      relationName: "tags",
    }),
  }),
);
export const relations_materials = relations(materials, ({ one, many }) => ({
  tags: many(materials_tags, {
    relationName: "tags",
  }),
  file: one(media, {
    fields: [materials.file],
    references: [media.id],
    relationName: "file",
  }),
}));
export const relations_homework = relations(homework, ({ one }) => ({
  student: one(students, {
    fields: [homework.student],
    references: [students.id],
    relationName: "student",
  }),
  material: one(materials, {
    fields: [homework.material],
    references: [materials.id],
    relationName: "material",
  }),
  submissionFile: one(media, {
    fields: [homework.submissionFile],
    references: [media.id],
    relationName: "submissionFile",
  }),
}));
export const relations_tests_questions_options = relations(
  tests_questions_options,
  ({ one }) => ({
    _parentID: one(tests_questions, {
      fields: [tests_questions_options._parentID],
      references: [tests_questions.id],
      relationName: "options",
    }),
  }),
);
export const relations_tests_questions_correct_answers = relations(
  tests_questions_correct_answers,
  ({ one }) => ({
    _parentID: one(tests_questions, {
      fields: [tests_questions_correct_answers._parentID],
      references: [tests_questions.id],
      relationName: "correctAnswers",
    }),
  }),
);
export const relations_tests_questions = relations(
  tests_questions,
  ({ one, many }) => ({
    _parentID: one(tests, {
      fields: [tests_questions._parentID],
      references: [tests.id],
      relationName: "questions",
    }),
    options: many(tests_questions_options, {
      relationName: "options",
    }),
    correctAnswers: many(tests_questions_correct_answers, {
      relationName: "correctAnswers",
    }),
  }),
);
export const relations_tests = relations(tests, ({ many }) => ({
  questions: many(tests_questions, {
    relationName: "questions",
  }),
}));
export const relations_payments = relations(payments, ({ one }) => ({
  student: one(students, {
    fields: [payments.student],
    references: [students.id],
    relationName: "student",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    studentsID: one(students, {
      fields: [payload_locked_documents_rels.studentsID],
      references: [students.id],
      relationName: "students",
    }),
    materialsID: one(materials, {
      fields: [payload_locked_documents_rels.materialsID],
      references: [materials.id],
      relationName: "materials",
    }),
    homeworkID: one(homework, {
      fields: [payload_locked_documents_rels.homeworkID],
      references: [homework.id],
      relationName: "homework",
    }),
    testsID: one(tests, {
      fields: [payload_locked_documents_rels.testsID],
      references: [tests.id],
      relationName: "tests",
    }),
    paymentsID: one(payments, {
      fields: [payload_locked_documents_rels.paymentsID],
      references: [payments.id],
      relationName: "payments",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  students_subjects: typeof students_subjects;
  students: typeof students;
  materials_tags: typeof materials_tags;
  materials: typeof materials;
  homework: typeof homework;
  tests_questions_options: typeof tests_questions_options;
  tests_questions_correct_answers: typeof tests_questions_correct_answers;
  tests_questions: typeof tests_questions;
  tests: typeof tests;
  payments: typeof payments;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_students_subjects: typeof relations_students_subjects;
  relations_students: typeof relations_students;
  relations_materials_tags: typeof relations_materials_tags;
  relations_materials: typeof relations_materials;
  relations_homework: typeof relations_homework;
  relations_tests_questions_options: typeof relations_tests_questions_options;
  relations_tests_questions_correct_answers: typeof relations_tests_questions_correct_answers;
  relations_tests_questions: typeof relations_tests_questions;
  relations_tests: typeof relations_tests;
  relations_payments: typeof relations_payments;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
