FROM excalidraw/excalidraw:latest

ARG VITE_WS_SERVER_URL=https://excalidraw-room.math-nastya.ru
ARG VITE_STORAGE_BACKEND_URL=https://excalidraw-api.math-nastya.ru/api/v2

ENV VITE_WS_SERVER_URL=$VITE_WS_SERVER_URL
ENV VITE_STORAGE_BACKEND_URL=$VITE_STORAGE_BACKEND_URL

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
